// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx9i2sFOEWtj-McTtzokKoBEKcXCSWGOI',
    appId: '1:29399630105:web:4935decf8c6eab7a290588',
    messagingSenderId: '29399630105',
    projectId: 'student-id-verification-1',
    authDomain: 'student-id-verification-1.firebaseapp.com',
    storageBucket: 'student-id-verification-1.appspot.com',
    measurementId: 'G-X35229DMQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvo8EwI3hLLkLwXNfIyEH7dtazYpwSHNA',
    appId: '1:29399630105:android:7a411fc8558edec7290588',
    messagingSenderId: '29399630105',
    projectId: 'student-id-verification-1',
    storageBucket: 'student-id-verification-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfltkW6kEA-9p3StCT5m-PrZ9NzN-hQdM',
    appId: '1:29399630105:ios:978984903b698227290588',
    messagingSenderId: '29399630105',
    projectId: 'student-id-verification-1',
    storageBucket: 'student-id-verification-1.appspot.com',
    iosBundleId: 'com.example.studentIdVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfltkW6kEA-9p3StCT5m-PrZ9NzN-hQdM',
    appId: '1:29399630105:ios:d4947d1e6f1711a4290588',
    messagingSenderId: '29399630105',
    projectId: 'student-id-verification-1',
    storageBucket: 'student-id-verification-1.appspot.com',
    iosBundleId: 'com.example.studentIdVerification.RunnerTests',
  );
}
